version: '3.4'

services:
  carmd.shell.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Live
      - ASPNETCORE_URLS=http://+:5003
    networks:
      shell_api_kiosk_network:
         ipv4_address: 172.123.1.1
    expose:
      - "5003"
    volumes:
      - .\CarMD.Shell.Api\Log:C:\app\log
networks:
  shell_api_kiosk_network:
    ipam:
      driver: default
      config:
         - subnet: 172.123.0.0/16